spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: 'jdbc:mysql://localhost:3306/gamingworld_aos'
        username: external
        password: XempreDB
        driver-class-name: com.mysql.cj.jdbc.Driver